### ISSUE TITLE
Add xenial template

### ISSUE THREAD

**Issue by k1-hedayati** [dhoppe/puppet-fail2ban#14] opened 2016-07-09 05:26 UTC
To avoid this error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/xenial/etc/fail2ban/jail.conf.erb' at /etc/puppetlabs/code/environments/production/modules/fail2ban/manifests/init.pp:65:26 on node core
```

When using fail2ban like this:

```
class { 'fail2ban':
    config_file_template => "fail2ban/${::lsbdistcodename}/etc/fail2ban/jail.conf.erb",
    package_ensure => 'latest',
  }
```

**Comment by k1-hedayati** [comment] 2016-07-09 06:01
Also using this config on xenial
```
  class { 'fail2ban':
    config_file_template => "fail2ban/trusty/etc/fail2ban/jail.conf.erb",
    package_ensure => 'latest',
  }
```
Causes this error:
```
Jul 09 10:24:32 core fail2ban-client[9971]: ERROR  Failed during configuration: While reading from '/etc/fail2ban/jail.conf' [line 156]: option 'port' in section 'pam-generic' already exists
Jul 09 10:24:32 core systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Jul 09 10:24:32 core systemd[1]: Failed to start Fail2Ban Service.
```

**Comment by k1-hedayati** [comment] 2016-07-09 07:27
Port actually defined twice in `[pam-generic]`
@dhoppe is this package broken?

**Comment by dhoppe** [comment] 2016-11-07 15:33
I am not able to reproduce this issue.

```
dhoppe@macbook ~/Projects/vagrant/multi-environment (git)-[master] % vagrant ssh ubuntu_14
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-36-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Mon Nov  7 16:17:29 2016 from 10.0.2.2
vagrant@ubuntu-14:~$ sudo /etc/init.d/fail2ban status
 * Status of authentication failure monitor
 *  fail2ban is running
```

Are you sure that you did not place any files under `/etc/fail2ban/jail.d/`?

FYI: I just added the support for Ubuntu 16.04.x (Xenial Xerus) and the service is also running.

**Comment by k1-hedayati** [comment] 2016-11-08 07:22
About xenial support it has been added with #15.
About port issue in `[pam-generic]` section, I'm not running puppet these days to test again, but if in your config port is defined twice and you can start fail2ban successfully then there is nothing to worry

**Comment by dhoppe** [comment] 2016-11-08 07:25
@k1-hedayati Thank you for the feedback. I will close this issue, since the configuration of `pam-generic` is part of the distributions packaging and the service starts without any error messages.

**Closed by dhoppe** 2016-11-08 07:25 UTC
